{"company": "ישראייר", "flightNumber": "\n                6H 044\n            ", "cameFrom": "\nאילת - רמון\n", "flightTime": "12/03 14:50", "finalTime": "15:29", "terminalNumber": "\n                1\n            ", "status": "עיכוב"}
{"company": "ברסלס איירליינס", "flightNumber": "\n                SN 7171\n            ", "cameFrom": "\nמינכן\n", "flightTime": "12/03 16:00", "finalTime": "16:00", "terminalNumber": "\n                3\n            ", "status": "מבוטלת"}
{"company": "ארקיע", "flightNumber": "\n                IZ 842\n            ", "cameFrom": "\nאילת - רמון\n", "flightTime": "12/03 16:00", "finalTime": "16:00", "terminalNumber": "\n                1\n            ", "status": "מבוטלת"}
{"company": "אל על", "flightNumber": "\n                LY 394\n            ", "cameFrom": "\nברצלונה\n", "flightTime": "12/03 16:40", "finalTime": "16:40", "terminalNumber": "\n                3\n            ", "status": "מבוטלת"}
{"company": "אמריקן איירליינס", "flightNumber": "\n                AA 8390\n            ", "cameFrom": "\nברצלונה\n", "flightTime": "12/03 16:40", "finalTime": "16:40", "terminalNumber": "\n                3\n            ", "status": "מבוטלת"}
{"company": "ישראייר", "flightNumber": "\n                6H 476\n            ", "cameFrom": "\nאילת - רמון\n", "flightTime": "12/03 16:50", "finalTime": "17:07", "terminalNumber": "\n                1\n            ", "status": "נחתה"}
{"company": "אל על", "flightNumber": "\n                LY 338\n            ", "cameFrom": "\nאמסטרדם\n", "flightTime": "12/03 17:00", "finalTime": "17:04", "terminalNumber": "\n                3\n            ", "status": "נחתה"}
{"company": "אל על", "flightNumber": "\n                LY 396\n            ", "cameFrom": "\nמדריד\n", "flightTime": "12/03 17:15", "finalTime": "17:11", "terminalNumber": "\n                3\n            ", "status": "נחתה"}
{"company": "AEROLINEASARGENTINAS", "flightNumber": "\n                AR 7872\n            ", "cameFrom": "\nמדריד\n", "flightTime": "12/03 17:15", "finalTime": "17:11", "terminalNumber": "\n                3\n            ", "status": "נחתה"}
{"company": "אמריקן איירליינס", "flightNumber": "\n                AA 8392\n            ", "cameFrom": "\nמדריד\n", "flightTime": "12/03 17:15", "finalTime": "17:11", "terminalNumber": "\n                3\n            ", "status": "נחתה"}
{"company": "LATAM", "flightNumber": "\n                LA 712\n            ", "cameFrom": "\nסאו פאולו\n", "flightTime": "12/03 17:25", "finalTime": "16:58", "terminalNumber": "\n                3\n            ", "status": "נחתה"}
{"company": "EasyJetEurope", "flightNumber": "\n                EJU 3737\n            ", "cameFrom": "\nפריס\n", "flightTime": "12/03 18:15", "finalTime": "18:00", "terminalNumber": "\n                3\n            ", "status": "סופי"}
{"company": "ישראייר", "flightNumber": "\n                6H 440\n            ", "cameFrom": "\nאילת - רמון\n", "flightTime": "12/03 18:30", "finalTime": "18:30", "terminalNumber": "\n                1\n            ", "status": "לא סופי"}
{"company": "איגיאן איירליינס", "flightNumber": "\n                A3 924\n            ", "cameFrom": "\nאתונה\n", "flightTime": "12/03 19:00", "finalTime": "19:00", "terminalNumber": "\n                3\n            ", "status": "מבוטלת"}
{"company": "ארקיע", "flightNumber": "\n                IZ 1802\n            ", "cameFrom": "\nאילת - רמון\n", "flightTime": "12/03 19:15", "finalTime": "19:15", "terminalNumber": "\n                1\n            ", "status": "מבוטלת"}
{"company": "INDIGO", "flightNumber": "\n                6E 4132\n            ", "cameFrom": "\nאיסטנבול\n", "flightTime": "12/03 19:20", "finalTime": "19:20", "terminalNumber": "\n                3\n            ", "status": "מבוטלת"}
{"company": "אייר אינדיה", "flightNumber": "\n                AI 139\n            ", "cameFrom": "\nדלהי\n", "flightTime": "12/03 19:25", "finalTime": "20:20", "terminalNumber": "\n                3\n            ", "status": "סופי"}
{"company": "טרנסאוויה", "flightNumber": "\n                HV 5799\n            ", "cameFrom": "\nאמסטרדם\n", "flightTime": "12/03 19:35", "finalTime": "19:10", "terminalNumber": "\n                3\n            ", "status": "סופי"}
{"company": "אל על", "flightNumber": "\n                LY 324\n            ", "cameFrom": "\nפריס\n", "flightTime": "12/03 20:00", "finalTime": "20:09", "terminalNumber": "\n                3\n            ", "status": "סופי"}
{"company": "אל על", "flightNumber": "\n                LY 9252\n            ", "cameFrom": "\nורשה\n", "flightTime": "12/03 20:10", "finalTime": "20:00", "terminalNumber": "\n                3\n            ", "status": "סופי"}
{"company": "לוט פוליש איירליינס", "flightNumber": "\n                LO 155\n            ", "cameFrom": "\nורשה\n", "flightTime": "12/03 20:10", "finalTime": "20:00", "terminalNumber": "\n                3\n            ", "status": "סופי"}
{"company": "ישראייר", "flightNumber": "\n                6H 448\n            ", "cameFrom": "\nאילת - רמון\n", "flightTime": "12/03 20:20", "finalTime": "20:20", "terminalNumber": "\n                1\n            ", "status": "לא סופי"}
{"company": "RYANAIR", "flightNumber": "\n                FR 1930\n            ", "cameFrom": "\nפוזנן\n", "flightTime": "12/03 20:40", "finalTime": "20:40", "terminalNumber": "\n                3\n            ", "status": "לא סופי"}
{"company": "אל על", "flightNumber": "\n                LY 316\n            ", "cameFrom": "\nלונדון\n", "flightTime": "12/03 21:05", "finalTime": "21:05", "terminalNumber": "\n                3\n            ", "status": "מבוטלת"}
{"company": "Blue Air", "flightNumber": "\n                0B 169\n            ", "cameFrom": "\nבוקרשט\n", "flightTime": "12/03 21:20", "finalTime": "21:20", "terminalNumber": "\n                3\n            ", "status": "מבוטלת"}
{"company": "אל על", "flightNumber": "\n                LY 9110\n            ", "cameFrom": "\nליסבון\n", "flightTime": "12/03 21:30", "finalTime": "21:30", "terminalNumber": "\n                3\n            ", "status": "מבוטלת"}
{"company": "RYANAIR", "flightNumber": "\n                FR 4103\n            ", "cameFrom": "\nפאפוס\n", "flightTime": "12/03 21:40", "finalTime": "21:40", "terminalNumber": "\n                3\n            ", "status": "לא סופי"}
{"company": "יונייטד איירליינס", "flightNumber": "\n                UA 954\n            ", "cameFrom": "\nסן פרנסיסקו\n", "flightTime": "12/03 21:40", "finalTime": "21:30", "terminalNumber": "\n                3\n            ", "status": "סופי"}
{"company": "אל על", "flightNumber": "\n                LY 2432\n            ", "cameFrom": "\nלרנקה\n", "flightTime": "12/03 21:45", "finalTime": "21:45", "terminalNumber": "\n                3\n            ", "status": "מבוטלת"}
{"company": "ATLANTIC", "flightNumber": "\n                VS 453\n            ", "cameFrom": "\nלונדון\n", "flightTime": "12/03 21:50", "finalTime": "21:50", "terminalNumber": "\n                3\n            ", "status": "מבוטלת"}
{"company": "ארקיע", "flightNumber": "\n                IZ 1806\n            ", "cameFrom": "\nאילת - רמון\n", "flightTime": "12/03 22:20", "finalTime": "22:20", "terminalNumber": "\n                1\n            ", "status": "מבוטלת"}
{"company": "אוקראיניין אינטרנשנל איירליינס", "flightNumber": "\n                PS 777\n            ", "cameFrom": "\nקייב\n", "flightTime": "12/03 22:40", "finalTime": "22:40", "terminalNumber": "\n                3\n            ", "status": "לא סופי"}
{"company": "ישראייר", "flightNumber": "\n                6H 894\n            ", "cameFrom": "\nטביליסי\n", "flightTime": "12/03 22:50", "finalTime": "22:50", "terminalNumber": "\n                3\n            ", "status": "לא סופי"}
{"company": "INDIGO", "flightNumber": "\n                6E 4130\n            ", "cameFrom": "\nאיסטנבול\n", "flightTime": "12/03 23:35", "finalTime": "23:35", "terminalNumber": "\n                3\n            ", "status": "לא סופי"}
{"company": "אל על", "flightNumber": "\n                LY 332\n            ", "cameFrom": "\nבריסל\n", "flightTime": "12/03 23:45", "finalTime": "23:45", "terminalNumber": "\n                3\n            ", "status": "לא סופי"}
{"company": "ישראייר", "flightNumber": "\n                6H 722\n            ", "cameFrom": "\nסופיה\n", "flightTime": "13/03 00:10", "finalTime": "00:10", "terminalNumber": "\n                3\n            ", "status": "לא סופי"}
{"company": "אל על", "flightNumber": "\n                LY 572\n            ", "cameFrom": "\nבוקרשט\n", "flightTime": "13/03 00:20", "finalTime": "00:20", "terminalNumber": "\n                3\n            ", "status": "מבוטלת"}
{"company": "אוקראיניין אינטרנשנל איירליינס", "flightNumber": "\n                PS 791\n            ", "cameFrom": "\nדנייפרו\n", "flightTime": "13/03 00:30", "finalTime": "00:30", "terminalNumber": "\n                3\n            ", "status": "מבוטלת"}
{"company": "אמריקן איירליינס", "flightNumber": "\n                AA 8382\n            ", "cameFrom": "\nפרנקפורט\n", "flightTime": "13/03 00:35", "finalTime": "00:35", "terminalNumber": "\n                3\n            ", "status": "לא סופי"}
{"company": "סיבריה איירליינס", "flightNumber": "\n                S7 4485\n            ", "cameFrom": "\nמוסקבה\n", "flightTime": "13/03 00:40", "finalTime": "00:40", "terminalNumber": "\n                3\n            ", "status": "לא סופי"}
{"company": "טורקיש איירליינס", "flightNumber": "\n                TK 810\n            ", "cameFrom": "\nאיסטנבול\n", "flightTime": "13/03 00:55", "finalTime": "00:55", "terminalNumber": "\n                3\n            ", "status": "לא סופי"}
{"company": "סוויס אינטרנשיונל איירליינס", "flightNumber": "\n                LX 4222\n            ", "cameFrom": "\nציריך\n", "flightTime": "13/03 02:10", "finalTime": "02:10", "terminalNumber": "\n                3\n            ", "status": "לא סופי"}
{"company": "אל על", "flightNumber": "\n                LY 352\n            ", "cameFrom": "\nמינכן\n", "flightTime": "13/03 02:15", "finalTime": "02:15", "terminalNumber": "\n                3\n            ", "status": "לא סופי"}
{"company": "דלתא איירליינס", "flightNumber": "\n                DL 9575\n            ", "cameFrom": "\nאמסטרדם\n", "flightTime": "13/03 02:45", "finalTime": "02:45", "terminalNumber": "\n                3\n            ", "status": "לא סופי"}
{"company": "אל על", "flightNumber": "\n                LY 8804\n            ", "cameFrom": "\nאדיס אבבה\n", "flightTime": "13/03 03:00", "finalTime": "03:00", "terminalNumber": "\n                3\n            ", "status": "לא סופי"}
{"company": "בולגריה אייר", "flightNumber": "\n                FB 573\n            ", "cameFrom": "\nסופיה\n", "flightTime": "13/03 03:00", "finalTime": "03:00", "terminalNumber": "\n                3\n            ", "status": "לא סופי"}
{"company": "אייר בלטיק", "flightNumber": "\n                BT 771\n            ", "cameFrom": "\nריגה\n", "flightTime": "13/03 03:50", "finalTime": "03:50", "terminalNumber": "\n                3\n            ", "status": "מבוטלת"}
{"company": "אייר סרביה", "flightNumber": "\n                JU 816\n            ", "cameFrom": "\nבלגראד\n", "flightTime": "13/03 04:15", "finalTime": "04:15", "terminalNumber": "\n                3\n            ", "status": "מבוטלת"}
{"company": "AEROMEXICO", "flightNumber": "\n                AM 7876\n            ", "cameFrom": "\nלונדון\n", "flightTime": "13/03 04:55", "finalTime": "04:55", "terminalNumber": "\n                3\n            ", "status": "לא סופי"}
{"company": "אל על", "flightNumber": "\n                LY 028\n            ", "cameFrom": "\nניוארק\n", "flightTime": "13/03 06:20", "finalTime": "06:20", "terminalNumber": "\n                3\n            ", "status": "לא סופי"}
{"company": "אל על", "flightNumber": "\n                LY 052\n            ", "cameFrom": "\nיוהנסבורג\n", "flightTime": "13/03 06:30", "finalTime": "06:30", "terminalNumber": "\n                3\n            ", "status": "לא סופי"}
{"company": "גאורגיאן איירוויז", "flightNumber": "\n                A9 695\n            ", "cameFrom": "\nטביליסי\n", "flightTime": "13/03 07:40", "finalTime": "07:40", "terminalNumber": "\n                3\n            ", "status": "מבוטלת"}
{"company": "יונייטד איירליינס", "flightNumber": "\n                UA 084\n            ", "cameFrom": "\nניוארק\n", "flightTime": "13/03 08:20", "finalTime": "08:20", "terminalNumber": "\n                3\n            ", "status": "לא סופי"}
{"company": "סיבריה איירליינס", "flightNumber": "\n                S7 4111\n            ", "cameFrom": "\nלרנקה\n", "flightTime": "13/03 08:30", "finalTime": "08:30", "terminalNumber": "\n                3\n            ", "status": "מבוטלת"}
{"company": "אייר מולדובה", "flightNumber": "\n                9U 547\n            ", "cameFrom": "\nקישינב\n", "flightTime": "13/03 08:50", "finalTime": "08:50", "terminalNumber": "\n                3\n            ", "status": "לא סופי"}
{"company": "פגסוס איירליינס", "flightNumber": "\n                PC 795\n            ", "cameFrom": "\nאיסטנבול\n", "flightTime": "13/03 09:10", "finalTime": "09:10", "terminalNumber": "\n                3\n            ", "status": "לא סופי"}
{"company": "ישראייר", "flightNumber": "\n                6H 422\n            ", "cameFrom": "\nאילת - רמון\n", "flightTime": "13/03 09:55", "finalTime": "09:55", "terminalNumber": "\n                1\n            ", "status": "לא סופי"}
{"company": "אל על", "flightNumber": "\n                LY 002\n            ", "cameFrom": "\nניו יורק\n", "flightTime": "13/03 10:15", "finalTime": "10:15", "terminalNumber": "\n                3\n            ", "status": "לא סופי"}
{"company": "AEROMEXICO", "flightNumber": "\n                AM 7868\n            ", "cameFrom": "\nניו יורק\n", "flightTime": "13/03 10:15", "finalTime": "10:15", "terminalNumber": "\n                3\n            ", "status": "לא סופי"}
{"company": "לוט פוליש איירליינס", "flightNumber": "\n                LO 159\n            ", "cameFrom": "\nקרקוב\n", "flightTime": "13/03 10:25", "finalTime": "10:25", "terminalNumber": "\n                3\n            ", "status": "לא סופי"}
{"company": "אֵרופלוט ראשן איירליינס", "flightNumber": "\n                SU 506\n            ", "cameFrom": "\nמוסקבה\n", "flightTime": "13/03 10:45", "finalTime": "10:45", "terminalNumber": "\n                3\n            ", "status": "מבוטלת"}
{"company": "LAUDA MOTION", "flightNumber": "\n                OE 186\n            ", "cameFrom": "\nוינה\n", "flightTime": "13/03 11:40", "finalTime": "11:40", "terminalNumber": "\n                3\n            ", "status": "לא סופי"}
{"company": "אֵרופלוט ראשן איירליינס", "flightNumber": "\n                SU 502\n            ", "cameFrom": "\nמוסקבה\n", "flightTime": "13/03 11:50", "finalTime": "11:50", "terminalNumber": "\n                3\n            ", "status": "לא סופי"}
{"company": "RYANAIR", "flightNumber": "\n                FR 6438\n            ", "cameFrom": "\nנירנברג\n", "flightTime": "13/03 12:00", "finalTime": "12:00", "terminalNumber": "\n                3\n            ", "status": "לא סופי"}
{"company": "נורוויג'ן אייר שאטל", "flightNumber": "\n                D8 5670\n            ", "cameFrom": "\nברצלונה\n", "flightTime": "13/03 12:10", "finalTime": "12:10", "terminalNumber": "\n                3\n            ", "status": "לא סופי"}
{"company": "RYANAIR", "flightNumber": "\n                FR 6754\n            ", "cameFrom": "\nבודפשט\n", "flightTime": "13/03 12:20", "finalTime": "12:20", "terminalNumber": "\n                3\n            ", "status": "לא סופי"}
{"company": "EasyJetEurope", "flightNumber": "\n                EJU 7933\n            ", "cameFrom": "\nאמסטרדם\n", "flightTime": "13/03 13:00", "finalTime": "13:00", "terminalNumber": "\n                3\n            ", "status": "לא סופי"}
{"company": "טרנסאוויה", "flightNumber": "\n                HV 6531\n            ", "cameFrom": "\nאיינדהובן\n", "flightTime": "13/03 13:10", "finalTime": "13:10", "terminalNumber": "\n                3\n            ", "status": "לא סופי"}
{"company": "אל על", "flightNumber": "\n                LY 016\n            ", "cameFrom": "\nבוסטון\n", "flightTime": "13/03 13:20", "finalTime": "13:20", "terminalNumber": "\n                3\n            ", "status": "לא סופי"}
{"company": "ישראייר", "flightNumber": "\n                6H 432\n            ", "cameFrom": "\nאילת - רמון\n", "flightTime": "13/03 13:40", "finalTime": "13:40", "terminalNumber": "\n                1\n            ", "status": "לא סופי"}
{"company": "AEROLINEASARGENTINAS", "flightNumber": "\n                AR 7850\n            ", "cameFrom": "\nמיאמי\n", "flightTime": "13/03 13:50", "finalTime": "13:50", "terminalNumber": "\n                3\n            ", "status": "לא סופי"}
{"company": "אל על", "flightNumber": "\n                LY 006\n            ", "cameFrom": "\nלוס אנג'לס\n", "flightTime": "13/03 14:00", "finalTime": "14:00", "terminalNumber": "\n                3\n            ", "status": "לא סופי"}
{"company": "AEROMEXICO", "flightNumber": "\n                AM 7856\n            ", "cameFrom": "\nניו יורק\n", "flightTime": "13/03 14:10", "finalTime": "14:10", "terminalNumber": "\n                3\n            ", "status": "לא סופי"}
{"company": "אל על", "flightNumber": "\n                LY 552\n            ", "cameFrom": "\nסופיה\n", "flightTime": "13/03 14:15", "finalTime": "14:15", "terminalNumber": "\n                3\n            ", "status": "לא סופי"}
{"company": "אמריקן איירליינס", "flightNumber": "\n                AA 8384\n            ", "cameFrom": "\nפרנקפורט\n", "flightTime": "13/03 15:00", "finalTime": "15:00", "terminalNumber": "\n                3\n            ", "status": "לא סופי"}
{"company": "אל על", "flightNumber": "\n                LY 358\n            ", "cameFrom": "\nפרנקפורט\n", "flightTime": "13/03 15:00", "finalTime": "15:00", "terminalNumber": "\n                3\n            ", "status": "לא סופי"}
{"company": "יונייטד איירליינס", "flightNumber": "\n                UA 090\n            ", "cameFrom": "\nניוארק\n", "flightTime": "13/03 15:20", "finalTime": "15:20", "terminalNumber": "\n                3\n            ", "status": "לא סופי"}
{"company": "איזי ג'ט", "flightNumber": "\n                EZY 2083\n            ", "cameFrom": "\nלונדון לוטון\n", "flightTime": "13/03 16:00", "finalTime": "16:00", "terminalNumber": "\n                3\n            ", "status": "לא סופי"}
{"company": "ארקיע", "flightNumber": "\n                IZ 828\n            ", "cameFrom": "\nאילת - רמון\n", "flightTime": "13/03 16:15", "finalTime": "16:15", "terminalNumber": "\n                1\n            ", "status": "מבוטלת"}
{"company": "ישראייר", "flightNumber": "\n                6H 440\n            ", "cameFrom": "\nאילת - רמון\n", "flightTime": "13/03 17:25", "finalTime": "17:25", "terminalNumber": "\n                1\n            ", "status": "לא סופי"}
{"company": "אל על", "flightNumber": "\n                LY 2366\n            ", "cameFrom": "\nבודפשט\n", "flightTime": "12/03 15:50", "finalTime": "15:50", "terminalNumber": "\n                3\n            ", "status": "מבוטלת"}
{"company": "יונייטד איירליינס", "flightNumber": "\n                UA 9471\n            ", "cameFrom": "\nמינכן\n", "flightTime": "12/03 16:00", "finalTime": "16:00", "terminalNumber": "\n                3\n            ", "status": "מבוטלת"}
{"company": "לופטהנזה ג'רמן איירליינס", "flightNumber": "\n                LH 688\n            ", "cameFrom": "\nמינכן\n", "flightTime": "12/03 16:00", "finalTime": "16:00", "terminalNumber": "\n                3\n            ", "status": "מבוטלת"}
{"company": "איבריה", "flightNumber": "\n                IB 2393\n            ", "cameFrom": "\nברצלונה\n", "flightTime": "12/03 16:40", "finalTime": "16:40", "terminalNumber": "\n                3\n            ", "status": "מבוטלת"}
{"company": "אל על", "flightNumber": "\n                LY 2522\n            ", "cameFrom": "\nפראג\n", "flightTime": "12/03 16:45", "finalTime": "16:45", "terminalNumber": "\n                3\n            ", "status": "נחתה"}
{"company": "ארקיע", "flightNumber": "\n                IZ 1844\n            ", "cameFrom": "\nאילת - רמון\n", "flightTime": "12/03 17:00", "finalTime": "17:15", "terminalNumber": "\n                1\n            ", "status": "נחתה"}
{"company": "אמריקן איירליינס", "flightNumber": "\n                AA 8379\n            ", "cameFrom": "\nאמסטרדם\n", "flightTime": "12/03 17:00", "finalTime": "17:04", "terminalNumber": "\n                3\n            ", "status": "נחתה"}
{"company": "איזי ג'ט", "flightNumber": "\n                EZY 8817\n            ", "cameFrom": "\nלונדון\n", "flightTime": "12/03 17:15", "finalTime": "16:55", "terminalNumber": "\n                3\n            ", "status": "נחתה"}
{"company": "איבריה", "flightNumber": "\n                IB 2395\n            ", "cameFrom": "\nמדריד\n", "flightTime": "12/03 17:15", "finalTime": "17:11", "terminalNumber": "\n                3\n            ", "status": "נחתה"}
{"company": "AEROMEXICO", "flightNumber": "\n                AM 7859\n            ", "cameFrom": "\nמדריד\n", "flightTime": "12/03 17:15", "finalTime": "17:11", "terminalNumber": "\n                3\n            ", "status": "נחתה"}
{"company": "ארקיע", "flightNumber": "\n                IZ 1812\n            ", "cameFrom": "\nאילת - רמון\n", "flightTime": "12/03 17:55", "finalTime": "17:55", "terminalNumber": "\n                1\n            ", "status": "מבוטלת"}
{"company": "איזי ג'ט", "flightNumber": "\n                EZY 2085\n            ", "cameFrom": "\nלונדון לוטון\n", "flightTime": "12/03 18:10", "finalTime": "17:50", "terminalNumber": "\n                3\n            ", "status": "סופי"}
{"company": "בולגריה אייר", "flightNumber": "\n                FB 571\n            ", "cameFrom": "\nסופיה\n", "flightTime": "12/03 18:30", "finalTime": "18:30", "terminalNumber": "\n                3\n            ", "status": "סופי"}
{"company": "LAUDA MOTION", "flightNumber": "\n                OE 186\n            ", "cameFrom": "\nוינה\n", "flightTime": "12/03 19:10", "finalTime": "19:00", "terminalNumber": "\n                3\n            ", "status": "סופי"}
{"company": "טורקיש איירליינס", "flightNumber": "\n                TK 788\n            ", "cameFrom": "\nאיסטנבול\n", "flightTime": "12/03 19:20", "finalTime": "19:20", "terminalNumber": "\n                3\n            ", "status": "מבוטלת"}
{"company": "RYANAIR", "flightNumber": "\n                FR 1868\n            ", "cameFrom": "\nמרסיי\n", "flightTime": "12/03 19:25", "finalTime": "19:05", "terminalNumber": "\n                3\n            ", "status": "סופי"}
{"company": "אורל איירליינס", "flightNumber": "\n                U6 721\n            ", "cameFrom": "\nסוצ'י\n", "flightTime": "12/03 19:30", "finalTime": "19:30", "terminalNumber": "\n                3\n            ", "status": "לא סופי"}
{"company": "איזי ג'ט", "flightNumber": "\n                EZY 1827\n            ", "cameFrom": "\nמנצ'סטר\n", "flightTime": "12/03 19:40", "finalTime": "19:30", "terminalNumber": "\n                3\n            ", "status": "סופי"}
{"company": "אמריקן איירליינס", "flightNumber": "\n                AA 8376\n            ", "cameFrom": "\nפריס\n", "flightTime": "12/03 20:00", "finalTime": "20:09", "terminalNumber": "\n                3\n            ", "status": "סופי"}
{"company": "אל על", "flightNumber": "\n                LY 8806\n            ", "cameFrom": "\nאדיס אבבה\n", "flightTime": "12/03 20:10", "finalTime": "19:20", "terminalNumber": "\n                3\n            ", "status": "סופי"}
{"company": "אתיופיאן איירלינס", "flightNumber": "\n                ET 414\n            ", "cameFrom": "\nאדיס אבבה\n", "flightTime": "12/03 20:10", "finalTime": "19:20", "terminalNumber": "\n                3\n            ", "status": "סופי"}
{"company": "ארקיע", "flightNumber": "\n                IZ 1846\n            ", "cameFrom": "\nאילת - רמון\n", "flightTime": "12/03 20:30", "finalTime": "20:30", "terminalNumber": "\n                1\n            ", "status": "מבוטלת"}
{"company": "ארקיע", "flightNumber": "\n                IZ 828\n            ", "cameFrom": "\nאילת - רמון\n", "flightTime": "12/03 21:05", "finalTime": "21:05", "terminalNumber": "\n                1\n            ", "status": "לא סופי"}
{"company": "אמריקן איירליינס", "flightNumber": "\n                AA 8372\n            ", "cameFrom": "\nלונדון\n", "flightTime": "12/03 21:05", "finalTime": "21:05", "terminalNumber": "\n                3\n            ", "status": "מבוטלת"}
{"company": "TP-AIRPORTUGAL", "flightNumber": "\n                TP 1603\n            ", "cameFrom": "\nליסבון\n", "flightTime": "12/03 21:30", "finalTime": "21:30", "terminalNumber": "\n                3\n            ", "status": "מבוטלת"}
{"company": "גאורגיאן איירוויז", "flightNumber": "\n                A9 699\n            ", "cameFrom": "\nטביליסי\n", "flightTime": "12/03 21:35", "finalTime": "21:35", "terminalNumber": "\n                3\n            ", "status": "לא סופי"}
{"company": "טורקיש איירליינס", "flightNumber": "\n                TK 864\n            ", "cameFrom": "\nאיסטנבול\n", "flightTime": "12/03 21:40", "finalTime": "21:40", "terminalNumber": "\n                3\n            ", "status": "לא סופי"}
{"company": "INDIGO", "flightNumber": "\n                6E 4126\n            ", "cameFrom": "\nאיסטנבול\n", "flightTime": "12/03 21:40", "finalTime": "21:40", "terminalNumber": "\n                3\n            ", "status": "לא סופי"}
{"company": "דלתא איירליינס", "flightNumber": "\n                DL 4420\n            ", "cameFrom": "\nלונדון\n", "flightTime": "12/03 21:50", "finalTime": "21:50", "terminalNumber": "\n                3\n            ", "status": "מבוטלת"}
{"company": "אוקראיניין אינטרנשנל איירליינס", "flightNumber": "\n                PS 781\n            ", "cameFrom": "\nקייב\n", "flightTime": "12/03 22:15", "finalTime": "22:15", "terminalNumber": "\n                3\n            ", "status": "מבוטלת"}
{"company": "ישראייר", "flightNumber": "\n                6H 814\n            ", "cameFrom": "\nסוצ'י\n", "flightTime": "12/03 22:40", "finalTime": "22:40", "terminalNumber": "\n                3\n            ", "status": "לא סופי"}
{"company": "רוייל ג'ורדניאן", "flightNumber": "\n                RJ 340\n            ", "cameFrom": "\nעמאן\n", "flightTime": "12/03 22:45", "finalTime": "22:45", "terminalNumber": "\n                3\n            ", "status": "לא סופי"}
{"company": "אֵרופלוט ראשן איירליינס", "flightNumber": "\n                SU 504\n            ", "cameFrom": "\nמוסקבה\n", "flightTime": "12/03 23:00", "finalTime": "23:00", "terminalNumber": "\n                3\n            ", "status": "לא סופי"}
{"company": "טורקיש איירליינס", "flightNumber": "\n                TK 790\n            ", "cameFrom": "\nאיסטנבול\n", "flightTime": "12/03 23:35", "finalTime": "23:35", "terminalNumber": "\n                3\n            ", "status": "לא סופי"}
{"company": "ישראייר", "flightNumber": "\n                6H 452\n            ", "cameFrom": "\nאילת - רמון\n", "flightTime": "12/03 23:55", "finalTime": "23:55", "terminalNumber": "\n                1\n            ", "status": "לא סופי"}
{"company": "פגסוס איירליינס", "flightNumber": "\n                PC 779\n            ", "cameFrom": "\nאיסטנבול\n", "flightTime": "13/03 00:10", "finalTime": "00:10", "terminalNumber": "\n                3\n            ", "status": "לא סופי"}
{"company": "אוקראיניין אינטרנשנל איירליינס", "flightNumber": "\n                PS 787\n            ", "cameFrom": "\nאודסה\n", "flightTime": "13/03 00:20", "finalTime": "00:20", "terminalNumber": "\n                3\n            ", "status": "מבוטלת"}
{"company": "אל על", "flightNumber": "\n                LY 356\n            ", "cameFrom": "\nפרנקפורט\n", "flightTime": "13/03 00:35", "finalTime": "00:35", "terminalNumber": "\n                3\n            ", "status": "לא סופי"}
{"company": "אל על", "flightNumber": "\n                LY 614\n            ", "cameFrom": "\nמוסקבה\n", "flightTime": "13/03 00:40", "finalTime": "00:40", "terminalNumber": "\n                3\n            ", "status": "לא סופי"}
{"company": "איגיאן איירליינס", "flightNumber": "\n                A3 928\n            ", "cameFrom": "\nאתונה\n", "flightTime": "13/03 00:50", "finalTime": "00:50", "terminalNumber": "\n                3\n            ", "status": "לא סופי"}
{"company": "INDIGO", "flightNumber": "\n                6E 4128\n            ", "cameFrom": "\nאיסטנבול\n", "flightTime": "13/03 00:55", "finalTime": "00:55", "terminalNumber": "\n                3\n            ", "status": "לא סופי"}
{"company": "אל על", "flightNumber": "\n                LY 344\n            ", "cameFrom": "\nציריך\n", "flightTime": "13/03 02:10", "finalTime": "02:10", "terminalNumber": "\n                3\n            ", "status": "לא סופי"}
{"company": "ק.ל.מ - נתיבי אוויר הולנדים", "flightNumber": "\n                KL 461\n            ", "cameFrom": "\nאמסטרדם\n", "flightTime": "13/03 02:45", "finalTime": "02:45", "terminalNumber": "\n                3\n            ", "status": "לא סופי"}
{"company": "טורקיש איירליינס", "flightNumber": "\n                TK 792\n            ", "cameFrom": "\nאיסטנבול\n", "flightTime": "13/03 02:50", "finalTime": "02:50", "terminalNumber": "\n                3\n            ", "status": "מבוטלת"}
{"company": "אתיופיאן איירלינס", "flightNumber": "\n                ET 404\n            ", "cameFrom": "\nאדיס אבבה\n", "flightTime": "13/03 03:00", "finalTime": "03:00", "terminalNumber": "\n                3\n            ", "status": "לא סופי"}
{"company": "לוט פוליש איירליינס", "flightNumber": "\n                LO 151\n            ", "cameFrom": "\nורשה\n", "flightTime": "13/03 03:35", "finalTime": "03:35", "terminalNumber": "\n                3\n            ", "status": "לא סופי"}
{"company": "בריטיש איירווייז", "flightNumber": "\n                BA 163\n            ", "cameFrom": "\nלונדון\n", "flightTime": "13/03 03:55", "finalTime": "03:55", "terminalNumber": "\n                3\n            ", "status": "מבוטלת"}
{"company": "אל על", "flightNumber": "\n                LY 318\n            ", "cameFrom": "\nלונדון\n", "flightTime": "13/03 04:55", "finalTime": "04:55", "terminalNumber": "\n                3\n            ", "status": "לא סופי"}
{"company": "אמריקן איירליינס", "flightNumber": "\n                AA 8373\n            ", "cameFrom": "\nלונדון\n", "flightTime": "13/03 04:55", "finalTime": "04:55", "terminalNumber": "\n                3\n            ", "status": "לא סופי"}
{"company": "QANTASAIRWAYS", "flightNumber": "\n                QF 5023\n            ", "cameFrom": "\nיוהנסבורג\n", "flightTime": "13/03 06:30", "finalTime": "06:30", "terminalNumber": "\n                3\n            ", "status": "לא סופי"}
{"company": "רוייל ג'ורדניאן", "flightNumber": "\n                RJ 342\n            ", "cameFrom": "\nעמאן\n", "flightTime": "13/03 06:50", "finalTime": "06:50", "terminalNumber": "\n                3\n            ", "status": "לא סופי"}
{"company": "RYANAIR", "flightNumber": "\n                FR 4161\n            ", "cameFrom": "\nפאפוס\n", "flightTime": "13/03 07:45", "finalTime": "07:45", "terminalNumber": "\n                3\n            ", "status": "לא סופי"}
{"company": "CYPRUSAIRWAYS", "flightNumber": "\n                CY 110\n            ", "cameFrom": "\nלרנקה\n", "flightTime": "13/03 08:30", "finalTime": "08:30", "terminalNumber": "\n                3\n            ", "status": "מבוטלת"}
{"company": "RYANAIR", "flightNumber": "\n                FR 5525\n            ", "cameFrom": "\nסלוניקי\n", "flightTime": "13/03 08:40", "finalTime": "08:40", "terminalNumber": "\n                3\n            ", "status": "לא סופי"}
{"company": "טורקיש איירליינס", "flightNumber": "\n                TK 784\n            ", "cameFrom": "\nאיסטנבול\n", "flightTime": "13/03 08:55", "finalTime": "08:55", "terminalNumber": "\n                3\n            ", "status": "לא סופי"}
{"company": "אייר קנדה", "flightNumber": "\n                AC 080\n            ", "cameFrom": "\nטורונטו\n", "flightTime": "13/03 09:15", "finalTime": "09:15", "terminalNumber": "\n                3\n            ", "status": "לא סופי"}
{"company": "RYANAIR", "flightNumber": "\n                FR 2823\n            ", "cameFrom": "\nאתונה\n", "flightTime": "13/03 10:05", "finalTime": "10:05", "terminalNumber": "\n                3\n            ", "status": "לא סופי"}
{"company": "אייר סיני", "flightNumber": "\n                4D 054\n            ", "cameFrom": "\nקהיר\n", "flightTime": "13/03 10:15", "finalTime": "10:15", "terminalNumber": "\n                3\n            ", "status": "לא סופי"}
{"company": "AEROLINEASARGENTINAS", "flightNumber": "\n                AR 7852\n            ", "cameFrom": "\nניו יורק\n", "flightTime": "13/03 10:15", "finalTime": "10:15", "terminalNumber": "\n                3\n            ", "status": "לא סופי"}
{"company": "אל על", "flightNumber": "\n                LY 9292\n            ", "cameFrom": "\nקרקוב\n", "flightTime": "13/03 10:25", "finalTime": "10:25", "terminalNumber": "\n                3\n            ", "status": "לא סופי"}
{"company": "RYANAIR", "flightNumber": "\n                FR 3606\n            ", "cameFrom": "\nממינגן\n", "flightTime": "13/03 11:10", "finalTime": "11:10", "terminalNumber": "\n                3\n            ", "status": "לא סופי"}
{"company": "טרנסאוויה", "flightNumber": "\n                HV 5801\n            ", "cameFrom": "\nאמסטרדם\n", "flightTime": "13/03 11:50", "finalTime": "11:50", "terminalNumber": "\n                3\n            ", "status": "לא סופי"}
{"company": "אל על", "flightNumber": "\n                LY 5088\n            ", "cameFrom": "\nסופיה\n", "flightTime": "13/03 11:50", "finalTime": "11:50", "terminalNumber": "\n                3\n            ", "status": "לא סופי"}
{"company": "איזי ג'ט שוויץ", "flightNumber": "\n                EZS 1525\n            ", "cameFrom": "\nז'נבה\n", "flightTime": "13/03 12:10", "finalTime": "12:10", "terminalNumber": "\n                3\n            ", "status": "לא סופי"}
{"company": "EasyJetEurope", "flightNumber": "\n                EJU 4783\n            ", "cameFrom": "\nברלין\n", "flightTime": "13/03 12:15", "finalTime": "12:15", "terminalNumber": "\n                3\n            ", "status": "לא סופי"}
{"company": "אל על", "flightNumber": "\n                LY 032\n            ", "cameFrom": "\nטורונטו\n", "flightTime": "13/03 12:50", "finalTime": "12:50", "terminalNumber": "\n                3\n            ", "status": "לא סופי"}
{"company": "אוקראיניין אינטרנשנל איירליינס", "flightNumber": "\n                PS 775\n            ", "cameFrom": "\nקייב\n", "flightTime": "13/03 13:05", "finalTime": "13:05", "terminalNumber": "\n                3\n            ", "status": "לא סופי"}
{"company": "אל על", "flightNumber": "\n                LY 026\n            ", "cameFrom": "\nניוארק\n", "flightTime": "13/03 13:20", "finalTime": "13:20", "terminalNumber": "\n                3\n            ", "status": "לא סופי"}
{"company": "אורל איירליינס", "flightNumber": "\n                U6 889\n            ", "cameFrom": "\nמוסקבה\n", "flightTime": "13/03 13:40", "finalTime": "13:40", "terminalNumber": "\n                3\n            ", "status": "לא סופי"}
{"company": "אל על", "flightNumber": "\n                LY 018\n            ", "cameFrom": "\nמיאמי\n", "flightTime": "13/03 13:50", "finalTime": "13:50", "terminalNumber": "\n                3\n            ", "status": "לא סופי"}
{"company": "AEROMEXICO", "flightNumber": "\n                AM 7874\n            ", "cameFrom": "\nלוס אנג'לס\n", "flightTime": "13/03 14:00", "finalTime": "14:00", "terminalNumber": "\n                3\n            ", "status": "לא סופי"}
{"company": "אל על", "flightNumber": "\n                LY 008\n            ", "cameFrom": "\nניו יורק\n", "flightTime": "13/03 14:10", "finalTime": "14:10", "terminalNumber": "\n                3\n            ", "status": "לא סופי"}
{"company": "AEROLINEASARGENTINAS", "flightNumber": "\n                AR 7856\n            ", "cameFrom": "\nניו יורק\n", "flightTime": "13/03 14:10", "finalTime": "14:10", "terminalNumber": "\n                3\n            ", "status": "לא סופי"}
{"company": "ישראייר", "flightNumber": "\n                6H 812\n            ", "cameFrom": "\nסוצ'י\n", "flightTime": "13/03 14:50", "finalTime": "14:50", "terminalNumber": "\n                3\n            ", "status": "לא סופי"}
{"company": "ישראייר", "flightNumber": "\n                6H 882\n            ", "cameFrom": "\nבאקו\n", "flightTime": "13/03 15:00", "finalTime": "15:00", "terminalNumber": "\n                3\n            ", "status": "לא סופי"}
{"company": "בריטיש איירווייז", "flightNumber": "\n                BA 165\n            ", "cameFrom": "\nלונדון\n", "flightTime": "13/03 15:15", "finalTime": "15:15", "terminalNumber": "\n                3\n            ", "status": "לא סופי"}
{"company": "EasyJetEurope", "flightNumber": "\n                EJU 5831\n            ", "cameFrom": "\nברלין\n", "flightTime": "13/03 15:45", "finalTime": "15:45", "terminalNumber": "\n                3\n            ", "status": "לא סופי"}
{"company": "דלתא איירליינס", "flightNumber": "\n                DL 468\n            ", "cameFrom": "\nניו יורק\n", "flightTime": "13/03 16:05", "finalTime": "16:05", "terminalNumber": "\n                3\n            ", "status": "לא סופי"}
{"company": "רוייל ג'ורדניאן", "flightNumber": "\n                RJ 344\n            ", "cameFrom": "\nעמאן\n", "flightTime": "13/03 16:55", "finalTime": "16:55", "terminalNumber": "\n                3\n            ", "status": "לא סופי"}
